require("anders.plugins-setup")
require("anders.core.options")
require("anders.core.keymaps")
require("anders.core.colorscheme")
require("anders.plugins.comment")
require("anders.plugins.nvim-tree")
require("anders.plugins.lualine")
require("anders.plugins.telescope")
require("anders.plugins.nvim-cmp")
require("anders.plugins.lsp.mason")
require("anders.plugins.lsp.lspsaga")
require("anders.plugins.lsp.lspconfig")
require("anders.plugins.lsp.null-ls")
require("anders.plugins.autopairs")
require("anders.plugins.treesitter")
require("anders.plugins.gitsigns")
require("anders.plugins.bufferline")
require("anders.plugins.harpoon")
require("anders.plugins.indent-blankline")
require("anders.plugins.omnisharp")
require("anders.plugins.treesitter-context")

-- -- wndow transparancy
vim.api.nvim_set_hl(0, "FloatBorder", { link = "Normal" })
vim.api.nvim_set_hl(0, "NormalFloat", { link = "Normal" })
vim.api.nvim_set_hl(0, "PMenu", { link = "Normal" })
vim.api.nvim_set_hl(0, "NormalNC", { link = "Normal" })

-- Set linenumber color
vim.api.nvim_command("highlight CursorLineNr guifg=#ffffff")
vim.api.nvim_command("highlight LineNr guifg=#a1a3a0")
-- vim.api.nvim_command("highlight LineNr guifg=#4ee9e4")
